blank_issues_enabled: true
contact_links:
  - name: Unrecognized Inverter
    url: https://github.com/wills106/homeassistant-solax-modbus/discussions?discussions_q=is%3Aopen+author%3Awills106+%22Unrecognized+Inverter%22
    about: If you see "unrecognized inverter type" error
  - name: GitHub Community Support
    url: https://github.com/wills106/homeassistant-solax-modbus/discussions
    about: Questions related to this integration belong here, general help, installation questions, supported Inverters.
